# Generated by Django 3.2.4 on 2021-06-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('total_population', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
            ],
        ),
    ]
