# Generated by Django 3.2.4 on 2021-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20210616_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='zero_to_six_total_population',
            field=models.CharField(choices=[('0-6 Age Male Population', '0-6 Age Male Population'), ('0-6 Age Female Population', '0-6 Age Female Population')], max_length=100),
        ),
    ]
